// Official SF Planning Department neighborhoods (36)
export const SF_NEIGHBORHOODS = [
  'Bayview/Hunters Point',
  'Bernal Heights',
  'Castro/Upper Market',
  'Chinatown',
  'Crocker Amazon',
  'Diamond Heights',
  'Excelsior',
  'Financial District/South Beach',
  'Glen Park',
  'Haight Ashbury',
  'Hayes Valley',
  'Inner Richmond',
  'Inner Sunset',
  'Lakeshore',
  'Marina',
  'Mission',
  'Mission Bay',
  'Nob Hill',
  'Noe Valley',
  'North Beach',
  'Oceanview/Merced/Ingleside',
  'Outer Mission',
  'Outer Richmond',
  'Pacific Heights',
  'Portola',
  'Potrero Hill',
  'Russian Hill',
  'Seacliff',
  'South of Market',
  'Sunset/Parkside',
  'Tenderloin',
  'Treasure Island',
  'Twin Peaks',
  'Visitacion Valley',
  'West of Twin Peaks',
  'Western Addition',
] as const

export type SFNeighborhood = (typeof SF_NEIGHBORHOODS)[number]
